### PR TITLE
Update build configuration

### PR DESCRIPTION
**Pull request by alecharp**
### Description

Updates Maven version used by wrapper to 3.9.6 and updated maven-wrapper version and scripts.

### Testing done

Ran `mvn verify` locally.

```[tasklist]
### Submitter checklist
- [ ] If an issue exists, it is well described and linked in the description
- [x] The description of this pull request is detailed and explain why this pull request is needed
- [x] The changeset is on a specific branch. Using `feature/` for new feature, or improvements ; Using `fix/` for bug fixes ; Using `docs/` for any documentation changes.
- [ ] If required, the documentation has been updated
- [x] There is automated tests to cover the code change / addition or an explanation why there is no tests in the description.
```

### CODE REVIEW

**Comment by alecharp** [comment]
@krisstern I'd be curious for you to test to build this pull request as I had to re-import the `.yarnrc.yml` because it is required for the `frontend-maven-plugin` to use Yarn 2+ in the `war` module, so I wonder what error you got and see what is missing in the documentation for you to build the project.

**Comment by krisstern** [comment]
Hi @alecharp Sure! Let me test now

**Comment by krisstern** [comment]
This pull request works for me

**Comment by alecharp** [comment]
Thanks for your time. Odd that the file was a problem in #421.

**Pull request merged**
