### PR TITLE
some relevant changes 

### LINKED ISSUE #193: Automatically removing old scores for each plugin
We can keep 5 or 10 scores for each plugins to get a trend, but we don't need to keep all the scores ever computed.
This needs to be scheduled and well tested.

- [ ] Removes scores for each plugins except the last 5 (by `computed_at`).
- [ ] Schedule this process to run every hour.
- [ ] This needs to be tested.

### PR DESCRIPTION
**Pull request by GauravFin**
resolved #193 

### Submitter checklist

- [ ] If the issue exists, it is well described and linked in the description
- [ ] The description of this pull request is detailed and explain why this pull request is needed
- [ ] The changeset is on a specific branch
  - `feature/` for new feature, or improvements
  - `fix/` for bug fixes
  - `docs/` for any documentation changes
- [ ] If required, the documentation has been updated
- [ ] There is automated tests to cover the code change / addition
    - If there is no test, include an explanation why in the description
- [ ] Run `mvn verify` locally and all tests are passing successfully
  - It is OK to create a pull request which has failing tests if it is created as a draft, is to fix a bug and the first commit is the test to prove the existence of the bug.
- [ ] There is no new warnings (checkstyle nor spotbugs) on the code

### CODE REVIEW

**Comment by alecharp** [comment]
I'm sorry, but have you tried to compile that code change locally. See #271 comment as well.

**Comment by alecharp** [comment]
@GauravFin have you been able to look at your pull request?

**Comment by alecharp** [comment]
@GauravFin your code is not compiling because you didn't:

- import `List` class
- you are trying to call `.stream` when you should be calling `.stream()` method
- import the `Scheduled` annotation

The scheduled method shouldn't be in the service class. 

If you don't have time to attend to your pull request, please close it.

**Comment by krisstern** [comment]
Hi @GauravFin Are you still working on this pull request?

**Pull request closed without merging**
