### PR TITLE
Sorted plugins on the basis of execution order

### PR DESCRIPTION
**Pull request by impact-maker**
Screenshot from 2023-01-26 21-21-14

Solves #65

### CODE REVIEW

**Comment by alecharp** [comment]
This is a lot like #109 without a way to sort from the front-end and without attributing the code to @dheerajodha. 
This is not a great way to do open-source in my opinion.

**Comment by jmMeessen** [comment]
Hello @impact-maker 
First of all, thank you and congratulations for your first pull request. 👍 

As you can see by yourself, there are a couple of things that need to be improved in order to get it moving. But this is normal: it is the learning process.

First of all, don't hesitate to over communicate. Especially in the PR's introduction. Just linking to the issue tends to be too short and counter productive. While the details are in the issue, don't hesitate to explain in 1 paragraph what your intent was, what method you used, any caveats (and as @alecharp mentioned, attribution of somebody else's code).
By doing this, you make the reviewer's work easier and more efficient (he often has a large number of such PR's to review.)

**Pro-tip**: while over communicating makes sure that all information is available to the reviewer, adding a one-liner TL;DR; (summary) removes even more un-necessary friction when skimming over a PR.

Another important thing, part of the OpenSource etiquette is that when the Continuous Integration of a PR fails (as in this case), it is important that you fix the problem asap, or mention that you are working to solve it, or request help to solve the problem. A reviewer will not look at a PR if the CI fails....
In this case, it looks like, at first sight, that there is a  problem at `PullRequestProbe.java:[48,8] 
 io.jenkins.pluginhealth.scoring.probes.PullRequestProbe is not abstract and does not override abstract method getOrder() in io.jenkins.pluginhealth.scoring.probes.Probe`.

Last, @alecharp 's remark is important: while OpenSource in its concept "allows" to pick up code where you want, it is important that you acknowledge and respect other people's work by mentioning that you were "largely inspired" by this person's code.

I am happy to discuss this and give more details and guidance in one of the Jenkins Gitter channels.

**Comment by krisstern** [comment]
Thanks @impact-maker for the contribution. But remember to refer to the previous PR on which this PR is based, best with a brief citation.

**Comment by alecharp** [comment]
I'm closing the pull request as it's not answering the problem targeted and it should have been best starting off from #109 work to acknowledge other contributors work.

**Pull request closed without merging**
