### PR TITLE
Disable spotless on tag

### PR DESCRIPTION
**Pull request by lemeurherve**
### Description

This PR disable spotless check when building a tag to avoid the following error:

> [ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.43.0:check (default) on project plugin-health-scoring-parent: Execution default of goal com.diffplug.spotless:spotless-maven-plugin:2.43.0:check failed: No such reference 'origin/main' -> [Help 1]

### Testing done

Tested with a replay of the v3.7.1 tag build on infra.ci.jenkins.io: https://infra.ci.jenkins.io/job/docker-jobs/job/plugin-health-scoring/view/tags/job/v3.7.1/8/console

```[tasklist]
### Submitter checklist
- [x] If an issue exists, it is well described and linked in the description
- [x] The description of this pull request is detailed and explain why this pull request is needed
- [ ] The changeset is on a specific branch. Using `feature/` for new feature, or improvements ; Using `fix/` for bug fixes ; Using `docs/` for any documentation changes.
- [ ] If required, the documentation has been updated
- [x] There is automated tests to cover the code change / addition or an explanation why there is no tests in the description.
```

### CODE REVIEW

**Review by alecharp — APPROVED** [review]
Thank you very much for your help!

**Comment by alecharp** [comment]
Merge queue was useful for dependency updates but it stopped working last week or so..

**Comment by lemeurherve** [comment]
> Merge queue was useful for dependency updates but it stopped working last week or so..

Due to this error?

**Comment by alecharp** [comment]
yes.

**Pull request merged**
