### PR TITLE
Enable Remote Development with Codespaces

### PR DESCRIPTION
**Pull request by MondalSayantan**
A codespace is a development environment that's hosted in the cloud. Each codespace you create is hosted by GitHub in a Docker container, running on a virtual machine. One can choose from a selection of virtual machine types, from 2 cores, 8 GB RAM, and 32 GB storage, up to 32 cores, 64 GB RAM, and 128 GB storage.

This PR adds the configuration to install and use correct versions of Java and Maven required for this project.

Note: Not to be confused with Gitpod

### CODE REVIEW

**Review by alecharp — CHANGES_REQUESTED** [review]
I'm not sure to see the problem with Gitpod however, if this helps contributing to the project, why not. 

I still have one questions on top of my suggestions: why do you need a PostgreSQL database if this is for development purpose?

**Comment by MondalSayantan** [comment]
Hi, I'll clarify the issue.

image
This is the error I get when I run the code in Gitpod
image

Same with Codespaces

**Comment by MondalSayantan** [comment]
I am really new with the devcontainer configuration for codespaces and development with Java in general. I just committed the boilerplate code that GitHub generated for me for Java.

I saw we have to populate the postgres credentials in the .env file, so inserted an configuration for that too.

**Comment by alecharp** [comment]
> I saw we have to populate the postgres credentials in the .env file, so inserted an configuration for that too.

the `.env` and the database are required to run the application, but not to fix a bug or implement a new feature.
So I'm not sure having the `postgres` container is needed.

**Comment by alecharp** [comment]
Ideally, you write tests, unit-tests and integration tests to validate your changes. That could apply to any development language, JavaScript included 😉 

If you want, you can use the `docker-compose` already present in the repository to start the application. Please, see https://github.com/jenkins-infra/plugin-health-scoring/blob/main/docs/CONTRIBUTING.adoc#how-to-run-the-application-locally

**Comment by MondalSayantan** [comment]
> Ideally, you write tests, unit-tests and integration tests to validate your changes. That could apply to any development language, JavaScript included wink
> 
That makes sense. Thanks!
I can't use Docker right now as I am limited by my system resources, so I have everything installed locally.

I could really use some help right now in understanding why I am getting this error even when I have my .env populated
image
`java.lang.RuntimeException: Driver org.postgresql.Driver claims to not accept jdbcUrl, jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
`

I am running this code `mvn spring-boot:run -Dskip.yarn -Dspring.profiles.active=dev`

**Comment by alecharp** [comment]
The `.env` file is used with Docker Compose. But as you are running the application with the Maven CLI, you need to `export` them in your terminal. Please see https://github.com/jenkins-infra/plugin-health-scoring/blob/main/docs/CONTRIBUTING.adoc#running-the-application-from-cli

**Comment by MondalSayantan** [comment]
> The `.env` file is used with Docker Compose. But as you are running the application with the Maven CLI, you need to `export` them in your terminal. Please see https://github.com/jenkins-infra/plugin-health-scoring/blob/main/docs/CONTRIBUTING.adoc#running-the-application-from-cli

Thank you!

**Comment by MondalSayantan** [comment]
Short summary of what I have achieved in the latest commit.

- I have removed PostgreSQL database as @alecharp pointed out was not required which I found out myself too after having a better grasp of the project.
- I have configured a `docker-outside-of-docker` in devcontainer.json. It's definition as I found it is `Re-use the host docker socket, adding the Docker CLI to a container. Feature invokes a script to enable using a forwarded Docker socket within a container to run Docker command.`
- Successfully tested by running the project on VS Code for Web. Attaching screenshot below
image

**Point to Note**: I have to manually forward the port 8080 after only which I can access URL

Some points I need help in understanding

1. I have used `docker-outside-of-docker`  instead of `docker-in-docker` just because the first option was letting me access the port, but I don't have the clarity why.
2. I ran the project in VSCode for Web. But sometimes (for some reasons not every time) when I try to run it on IntelliJ Idea through Jetbrains Gateway, I get a SSH error. I think this might be related to this post https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host. I need some help in understanding how to go forward to resolve this SSH issue because as far as I understand it would vary from user to user

**Comment by alecharp** [comment]
I'm puzzled. The PostgreSQL database should be required to run the application. I thought this was about being able to contribute to the project from VSCode with some kind of pre-filled environment. 

How is this different from #209? Are the two pull requests doing the same thing but on different platform?

**Comment by MondalSayantan** [comment]
> I'm puzzled. The PostgreSQL database should be required to run the application. I thought this was about being able to contribute to the project from VSCode with some kind of pre-filled environment.
> 
I think I am not able to convey my message. On opening a github codespace from the web, an environment is generated with the configuration I have committed. This environment allows to run the docker commands which generates a PostgreSQL on its own. I removed PostgreSQL with the thought that it might be unnecessary if we have the option of doing the same thing using Docker.

Should I add it again?

> How is this different from #209? Are the two pull requests doing the same thing but on different platform?
#209 is about development using Gitpod. #208 is for development with Github Codespaces

**Comment by MondalSayantan** [comment]
I have an environment in Github codespace prefilled with

- Java 17
- NodeJS
- Yarn
- Docker

**Comment by alecharp** [comment]
Is this still a draft @MondalSayantan ?

**Comment by MondalSayantan** [comment]
Hi @alecharp,

This PR is still in draft as I was focused on my other two PRs. 

Also, after some research and talking to people, I have come to know that not many people know and use Github codespaces as their development environment. Most people prefer Gitpod(#209). I was wondering if my work on this PR would be helpful to the community. 

I know I might be asking this question very late, but I did not realize this when I opened this PR. It would be extremely helpful for me if you could provide your wisdom on this.

**Comment by MondalSayantan** [comment]
Rewrote the complete devcontainer.json file to tackle the basic issues first, i.e, installation of correct Java and Maven version. 
Verified it by running `mvn verify` locally.

**Comment by alecharp** [comment]
I'm closing this pull request because I don't see the need for it. The fact that no one asked to get it merged over the past year illustrate my point. 
@MondalSayantan Thank you for the time you dedicated to the project, but this doesn't seem to be to the benefit of the project.

**Pull request closed without merging**
